version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: electron-updater-nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
